name: Healthcheck

on:
  schedule:
    - cron: "*/5 * * * *"   # каждые 5 минут
  workflow_dispatch:        # возможность запустить вручную

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      fail-fast: false
      matrix:
        url:
          - "https://adam-devops.ru"
          - "https://www.adam-devops.ru"
    steps:
      - name: Curl ${{ matrix.url }}
        id: curl
        run: |
          set -euo pipefail
          for i in 1 2 3; do
            code=$(curl -k -sS -o /dev/null -w "%{http_code}" --max-time 15 "${{ matrix.url }}")
            echo "HTTP ${code}"
            if [ "$code" = "200" ]; then exit 0; fi
            sleep 5
          done
          echo "status=$code" >> "$GITHUB_OUTPUT"
          exit 1

  alert:
    needs: check
    if: failure()           # запускается только если check упал
    runs-on: ubuntu-latest
    steps:
      - name: Open GitHub Issue
        uses: actions/github-script@v7
        with:
          script: |
            const title = `Healthcheck failed: ${new Date().toISOString()}`;
            const body = [
              `Healthcheck failed on branch: ${context.ref}`,
              `Run: ${context.runNumber}`,
              `See logs: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
            ].join('\n');
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title, body, labels: ['healthcheck','incident']
            });

