name: OIDC Check

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> "$GITHUB_PATH"
          export PATH="$HOME/yandex-cloud/bin:$PATH"

      - name: Check yc version
        run: yc --version

      - name: Get GitHub OIDC ID token
        id: oidc
        run: |
          set -euo pipefail
          TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Exchange OIDC ID token for IAM token
        run: |
          IAM_TOKEN=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -d "{\"identityToken\": \"${TOKEN}\"}" \
            "https://iam.api.cloud.yandex.net/iam/v1/tokens" | jq -r '.iamToken')
          echo "IAM_TOKEN=$IAM_TOKEN" >> $GITHUB_ENV

      - name: Configure YC CLI with IAM token
        run: |
          yc config profile create github-oidc
          yc config set cloud-id "${{ secrets.YC_CLOUD_ID }}"
          yc config set folder-id "${{ secrets.YC_FOLDER_ID }}"
          yc config set token "$IAM_TOKEN"
          yc --version

      - name: Who am I in Yandex Cloud
        run: yc iam whoami

      - name: Assert SA is ci-oidc-sa
        run: |
          yc iam whoami --format json | jq -re '.service_account.name=="ci-oidc-sa"'

