name: OIDC Check

on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "${HOME}/yandex-cloud/bin" >> "$GITHUB_PATH"

      - name: Get YC IAM token via GitHub OIDC
        run: |
          yc --version
          yc iam create-token --jwt-from-oidc > token.txt
          echo "YC_IAM_TOKEN=$(cat token.txt)" >> "$GITHUB_ENV"

      - name: Who am I in Yandex Cloud
        run: |
          yc iam whoami --format json --token "${{ env.YC_IAM_TOKEN }}" | tee whoami.json
          echo "Parsed service_account_id:"
          cat whoami.json | jq -r '.service_account_id // .user_account.id // "unknown"'

      - name: Assert SA is ci-oidc-sa
        env:
          EXPECTED_SA_ID: "aje94h2634726c8ivghr"   # <-- твой ci-oidc-sa
        run: |
          SA_ID=$(jq -r '.service_account_id // empty' whoami.json)
          if [ -z "$SA_ID" ]; then
            echo "Not a service account token (maybe user?)"; exit 1
          fi
          test "$SA_ID" = "$EXPECTED_SA_ID" || { echo "Unexpected SA: $SA_ID"; exit 1; }
          echo "OK: OIDC issued token for $SA_ID"

