name: OIDC Check

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> "$GITHUB_PATH"
      
      - name: Check yc version
        run: yc --version
      
      - name: Get GitHub OIDC ID token
        id: gh_oidc
        env:
          AUDIENCE: yandex-cloud
        run: |
          set -euo pipefail
          REQ_URL="${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=${AUDIENCE}"
          RESP="$(curl -sSf \
            -H "Authorization: Bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
            "$REQ_URL")"
          TOKEN="$(echo "$RESP" | jq -r '.value')"
          echo "token=$TOKEN" >> "$GITHUB_OUTPUT"

      - name: Configure yc profile (OIDC)
        run: |
          yc config profile create github-oidc
          yc config set cloud-id  "${{ secrets.YC_CLOUD_ID }}"
          yc config set folder-id "${{ secrets.YC_FOLDER_ID }}"
          yc config set token     "${{ steps.gh_oidc.outputs.token }}"

      - name: Who am I in Yandex Cloud
        run: yc iam whoami

      - name: Assert SA is ci-oidc-sa
        run: |
          yc iam whoami --format json | jq -re '.service_account.name=="ci-oidc-sa"'

