name: OIDC Check

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Install tools (yc + jq)
        run: |
          set -euo pipefail
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> "$GITHUB_PATH"
          sudo apt-get update -y
          sudo apt-get install -y jq
          yc --version

      # 1) Берём GitHub OIDC ID-токен (audience = yandex-cloud)
      - name: Get GitHub OIDC ID token
        id: gh_oidc
        env:
          AUDIENCE: yandex-cloud
        run: |
          set -euo pipefail
          REQ_URL="${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=${AUDIENCE}"
          RESP="$(curl -sSf -H "Authorization: Bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" "$REQ_URL")"
          ID_TOKEN="$(echo "$RESP" | jq -r '.value')"
          echo "id_token=$ID_TOKEN" >> "$GITHUB_OUTPUT"

      # 2) Меняем ID-токен -> IAM-токен (через публичный IAM API)
      - name: Exchange OIDC ID token for IAM token
        id: iam
        run: |
          set -euo pipefail
          IAM_TOKEN="$(curl -sSf \
            -H "Content-Type: application/json" \
            -d "{\"jwt\":\"${{ steps.gh_oidc.outputs.id_token }}\"}" \
            https://iam.api.cloud.yandex.net/iam/v1/tokens | jq -r '.iamToken')"
          echo "iam_token=$IAM_TOKEN" >> "$GITHUB_OUTPUT"

      # 3) Конфигурируем профиль yc этим IAM-токеном
      - name: Configure yc profile (OIDC/IAM)
        run: |
          set -euo pipefail
          yc config profile create github-oidc
          yc config set cloud-id  "${{ secrets.YC_CLOUD_ID }}"
          yc config set folder-id "${{ secrets.YC_FOLDER_ID }}"
          yc config set token     "${{ steps.iam.outputs.iam_token }}"

      - name: Who am I in Yandex Cloud
        run: yc iam whoami

      - name: Assert SA is ci-oidc-sa
        run: |
          yc iam whoami --format json | jq -re '.service_account.name=="ci-oidc-sa"'

