name: OIDC Check

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> "$GITHUB_PATH"
          yc --version

      - name: Get YC IAM token via GitHub OIDC
        run: |
          yc config profile create github-oidc
          yc config set cloud-id "${{ secrets.YC_CLOUD_ID }}"
          yc config set folder-id "${{ secrets.YC_FOLDER_ID }}"
          # Обмен GitHub OIDC → YC IAM
          yc config set token "$(yc iam create-token)"

      - name: Who am I in Yandex Cloud
        run: yc iam whoami

      - name: Assert SA is ci-oidc-sa
        run: |
          yc iam whoami --format json | jq -re '.service_account.name=="ci-oidc-sa"'

